### Automatic Makefile generation by 'genmake' script        ####
### Copyright, Jerry Cooperstein, coop@linuxfoundation.org 2/2003 - 1/2016 ####
### License: GPLv2 ###

justdoit:
	gcc my_getcpu.c -o my_getcpu 

clean: 
	rm my_getcpu
